pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Code checked out'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd ace/backend
                docker build -t ace-backend:latest .
                '''
            }
        }

        stage('Load Image into KIND') {
            steps {
                sh '''
                kind load docker-image ace-backend:latest --name enterprise-api
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f k8s/ace-deployment.yaml
                kubectl apply -f k8s/ace-service.yaml
                '''
            }
        }
    }
}

